version: '2'

services:
  Dev:
    image: dicecord
    build: .
    volumes:
      - /root/dicecord/db:/usr/src/dicecord/db
      - /etc/timezone:/etc/timezone:ro
    restart: always
    command: node dicecord.js --test
  Niven:
    image: dicecord
    build: .
    volumes:
      - /root/dicecord/db:/usr/src/dicecord/db
      - /etc/timezone:/etc/timezone:ro
    restart: always
    command: node dicecord.js --niven
  Nyria:
    image: dicecord
    build: .
    volumes:
      - /root/dicecord/db:/usr/src/dicecord/db
      - /etc/timezone:/etc/timezone:ro
    restart: always 
    command: node dicecord.js --nyria